version: "3.9"

services:
  webserver:
    build: 
      context: bin/python
    command: python manage.py runserver 0.0.0.0:8000
    container_name: 'python'
    ports:
      - "8000:8000"
    links: 
      - mysql
    volumes: 
      - ./www:/usr/src/app
    networks:
      - dev-network
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge